name: Ruff
on: [pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v3

      - uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          src: src/ examples/ tests/
          args: check --no-fix

      - uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          src: src/ examples/ tests/
          args: format --diff
