name: Ruff
on: [pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - uses: chartboost/ruff-action@v1
        with:
          src: src/ examples/ tests/
          args: check --no-fix

      - uses: chartboost/ruff-action@v1
        with:
          src: src/ examples/ tests/
          args: format --diff
