name: Test

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11.4
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: "poetry"
          architecture: 'x64'
      - name: Install dependencies
        run: poetry install --all-extras

      - name: Run tests
        run: poetry run pytest -vv tests/
        env:
          LOG10_URL: "https://log10.io"
          LOG10_ORG_ID: ${{ secrets.LOG10_ORG_ID }}
          LOG10_TOKEN: ${{ secrets.LOG10_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          LAMINI_API_KEY: ${{ secrets.LAMINI_API_KEY }}
          GOOGLE_API_KEY : ${{ secrets.GOOGLE_API_KEY }}
